from faker import Faker

"""
More info: https://microservices-demo.github.io/docs/user-accounts.html
"""

# The demo app is shipped with the following account:
username = 'user'
password = 'password'

# Fake data that is used for new registrations:
faker = Faker()
autogenerated_username = faker.user_name()
autogenerated_first_name = faker.first_name()
autogenerated_last_name = faker.last_name()
autogenerated_email = faker.email()
autogenerated_password = faker.password()
